### PR TITLE
builtin: rename type to "builtin_function_or_method"

### PR DESCRIPTION
**Pull request by alandonovan**
Also:
- remove all uses of "builtin" as a noun.
  Now it's always "built-in function" (or method).

### CODE REVIEW

**Comment by brandjon** [comment]
The type() result string can still be "builtin", but if that's too vague, "builtin_function" would be more concise than "builtin_function_or_method". Methods are functions, after all. And if you create an object in Skylark code by writing "o.f = lambda ...", then "type(o.f)" will still say "function" rather than "method".

**Comment by alandonovan** [comment]
I chose builtin_function_or_method because that's what Python does.  It may be long but it's self-explanatory.

**Comment by brandjon** [comment]
Python isn't too consistent on that account. It exposes the implementation details in the type name -- sometimes returning "method descriptor" or "type". There's also precedent for breaking with Python's naming scheme, in the case of "str" vs "string" for type("abc"). But if you think the long name's better then I don't have a strong objection.

**Comment by alandonovan** [comment]
No strong opinion. I'll let y'all decide.

**Comment by brandjon** [comment]
Currently the java implementation uses "function" for builtin functions. (Accessing builtin methods as first-class values isn't supported yet.)

In the absence of strong reasons to the contrary, we'd like to avoid the extra churn. Is there good reason to distinguish between functions implemented natively and functions implemented in Skylark?

**Comment by alandonovan** [comment]
On 18 October 2017 at 15:47, Jon Brandvein <notifications@github.com> wrote:

> Currently the java implementation uses "function" for builtin functions.
> (Accessing builtin methods as first-class values isn't supported yet.)
>
> In the absence of strong reasons to the contrary, we'd like to avoid the
> extra churn. Is there good reason to distinguish between functions
> implemented natively and functions implemented in Skylark?
>
Yes: they're different concrete types. Just because they are both callable
doesn't mean they can be used in the same places.  For example, a
'function' (defined in Skylark) has a parameter list.  Even though you can't
access it from within the language, it's there and it affects the behavior
of Skylark programs.  For example, Bazel requires a function (not an
arbitrary callable) for its implicit outputs feature, and it calls the
function with a sequence of values that depends on its parameter list.

**Comment by alandonovan** [comment]
On 18 October 2017 at 18:08, Alan Donovan <adonovan@google.com> wrote:

> For example, a 'function' (defined in Go) has a parameter list.
>

Sorry, "defined in Skylark".

**Review by jayconrod — APPROVED** [review]
LGTM.

In hindsight, I think "native" would have been a better word "builtin", but Builtin and NewBuiltin are part of the API, so it's too late to change.

"builtin_function_or_method" is fine, but I think it would be fine to leave it as "builtin", too.

**Comment by brandjon** [comment]
I'm not sure I buy that Skylark-defined and native-defined functions have fundamentally different interfaces. In what way do native functions lack parameter lists? Is it that they can have unnamed, positional-only arguments? Because aside from that they should be identical.

The fact that they're different concrete types is an implementation detail. Having type() differ for builtins would be exposing that implementation detail, just like Python does with type(repr) vs type(str) vs type(str.replace).

If Bazel can't pass a builtin method as an implicit output function, I'd consider that a quirk or even a bug, not a design feature.

**Comment by alandonovan** [comment]
On 19 October 2017 at 08:42, Jon Brandvein <notifications@github.com> wrote:

> I'm not sure I buy that Skylark-defined and native-defined functions have
> fundamentally different interfaces.
>
> In what way do native functions lack parameter lists? Is it that they can
> have unnamed, positional-only arguments? Because aside from that they
> should be identical.
>
A callable value is one that can be called with a sequence of positional
arguments and a sequence of named arguments.  (*args and **kwargs arguments
are flattened out on the caller side of the calling convention.)  A
Skylark-defined function (type "function") interprets the args and kwargs
using its parameter list.  By contrast, a built-in function is free to
interpret the args and kwargs in any manner it chooses.  As you point out,
built-in functions routinely accept unnamed positional-only arguments. As
another example, a built-in function may require that a certain parameter
is always specified by name, not position, as int(...) does with its 'base'
parameter. All of this is inherited from Python.

The fact that they're different concrete types is an implementation detail.
>
Bazel's output function mechanism clearly proves this false.

If Bazel can't pass a builtin method as an implicit output function, I'd
> consider that a quirk or even a bug, not a design feature.
>
Whether Bazel's use of reflection over the parameter list is good design is
a separate conversation, but as long as it does, it needs a way to extract
a list of parameter names from a function.  In general, built-in functions
have no such list, nor should they.

Focus on the "callable" abstraction.  We don't unify tuples and lists even
though they are similar in many ways.  Instead we define type abstractions
(iterable, sequence, etc) and specify which of these is needed in a given
context.


> Having type() differ for builtins would be exposing that implementation
> detail, just like Python does with type(repr) vs type(str) vs
> type(str.replace).
>
The type function reports the concrete type of its argument, as it should,
as a concrete type in Python (and Skylark) may satisfy many different type
abstractions and it would be wrong for type(x) to pick just one.  repr,
str, and str.replace are all different types of callable, but there plenty
of other concrete types are callable, such as a 'rule' in Bazel.  Should
type(rule) return "function" too?

**Comment by brandjon** [comment]
> Whether Bazel's use of reflection over the parameter list is good design is
a separate conversation, but as long as it does, it needs a way to extract
a list of parameter names from a function.

Sorry, I forgot that implicit output functions were weird that way.

> In general, built-in functions have no such list, nor should they.

I see your point about there being an interface that's not satisfied. We could satisfy it in the trivial way: the get-named-parameters operation of builtins may simply return fewer parameters than actually exist.

I am generally fine with allowing type() to elide concrete information that the caller doesn't need. For instance, the return type of glob() is a list, even though its concrete implementation is special-cased (it's the same Java class with a different internal representation).

The rule() example is more compelling. But I'm not sure that just because callable is an interface means that builtin implementations can't masquerade with Skylark-defined functions.

In any case, we already did a deprecation and migration for str/repr representations in the Java implementation. I don't know that we have the stomach for another one over just this issue. But maybe if we migrate go from "type()" to "typename()" we could change some return values then.

**Comment by brandjon** [comment]
To clarify, I think the Java implementation will likely remain as it is, possibly even into 1.0, so this should be added to the appendix of differences with the Java implementation.

**Comment by dslomov** [comment]
Whan @brandjon says. The churn is not worth it.

**Comment by alandonovan** [comment]
On 19 October 2017 at 11:33, Dmitry Lomov <notifications@github.com> wrote:

> The churn is not worth it.
>
What churn are we talking about?  The string "function" appears in only 12
.bzl files in the tree, so I assume you don't mean churn from changing the
type string for built-in functions.

**Comment by dslomov** [comment]
This means the incompatible change flag, associated documentation and going over external repositories. Sorry, not happening for this change.

**Comment by alandonovan** [comment]
My point is that the incompatible flag change process may be unnecessary: AFAICT, the only place in the entire tree where it matters is gen_targets_with_configs.bzl:116.

**Comment by dslomov** [comment]
Our commitment to external users is incompatible change flag. So, yes, necessary.

**Pull request merged**
